# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 062a13780904605f51d53efd81d5219c803d4afc8c2b29a08c88cb0e0f612864d001ccfe3c84eb3ab8d6af8c3bb2d99ac172180e41db6cf9afba79a0c864c87b

test:
  secret_key_base: ff816dc5b98a56a9b865e374e176056b5ab710cc2c4c9669a161f344d06f47b5ce214677dbbac69e0ae4aeb1899dbe4a5a8f12a5935674a2bc989564fd959fe2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
